### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [dracula/gnome-terminal#1]
Hello @GalaticStryder!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by GalaticStryder** [comment]
@zenorocha That's fine, all we need is the website part of it. If you can create the page on the website, I can add the instructions and preview there. I've just updated it, working good on zsh and fish shells.

**Comment by zenorocha** [comment]
Just noticed a typo on my last message, sorry about that.

I sent you an invitation to join the org, let me know when you get it.

**Comment by GalaticStryder** [comment]
@zenorocha Done, could you push master branch to dracula organization? I think the repo name should be **gnome-terminal**.

**Comment by zenorocha** [comment]
I think transferring the repository is easier. I changed your permissions so you should be able to do it now.

**Comment by zenorocha** [comment]
`gnome-terminal` sounds good to me.

**Comment by GalaticStryder** [comment]
Done, will proceed with a faster installer and deploy to the website.
